FROM ubuntu:20.04

ARG HUGO_VERSION=0.81.0

ENV DOCUMENT_DIR=/hugo-project

# python-minimal for pygments support for asciidoctor
RUN apt-get update && apt-get upgrade -y \
    && DEBIAN_FRONTEND=noninteractive apt-get install -y --no-install-recommends \
    curl ruby ruby-dev make cmake build-essential bison flex graphviz \
    openjdk-11-jre python \
    && apt-get clean \
    && rm -rf /var/lib/apt/lists/* \
    && rm -rf /tmp/*

# install plantuml
RUN mkdir -p /opt/plantuml && cd /opt/plantuml \
    && UML=http://sourceforge.net/projects/plantuml/files/plantuml.jar/download \
    && curl -JLO ${UML}
COPY ./docker_assets/plantuml /usr/local/bin/plantuml
RUN chmod a+x /usr/local/bin/plantuml

# install ASCIIDOC support
RUN gem install --no-document asciidoctor asciidoctor-revealjs asciidoctor-html5s \
    rouge asciidoctor-confluence asciidoctor-diagram coderay pygments.rb

# Use the specific Hugo version for consistency
ADD https://github.com/gohugoio/hugo/releases/download/v${HUGO_VERSION}/hugo_${HUGO_VERSION}_Linux-64bit.tar.gz /tmp/hugo.tgz

RUN cd /usr/local/bin && tar -xzf /tmp/hugo.tgz && rm /tmp/hugo.tgz

RUN mkdir ${DOCUMENT_DIR}
WORKDIR ${DOCUMENT_DIR}

VOLUME ${DOCUMENT_DIR}
ENV CLASSPATH=/opt/plantuml
ENV PATH=${DOCUMENT_DIR}:$PATH
CMD ["hugo","server","--bind","0.0.0.0"]

HEALTHCHECK --interval=2s --timeout=3s \
  CMD curl -f http://localhost:1313/ || exit 1

