FROM public.ecr.aws/ubuntu/ubuntu:20.04_stable

ARG HUGO_VERSION=0.82.0

ENV DOCUMENT_DIR=/hugo-project
ENV PATH="${PATH}:/usr/local/go/bin"

# python-minimal for pygments support for asciidoctor
RUN apt-get update && apt-get upgrade -y \
    && DEBIAN_FRONTEND=noninteractive apt-get install -y --no-install-recommends \
    curl ruby ruby-dev make cmake build-essential bison flex graphviz \
    openjdk-11-jre python git \
    && apt-get clean \
    && rm -rf /var/lib/apt/lists/*

# Install golang
RUN cd /tmp \
    && curl -JLO https://golang.org/dl/go1.16.3.linux-amd64.tar.gz \
    && rm -rf /usr/local/go && tar -C /usr/local -xzf go1.16.3.linux-amd64.tar.gz

# Download Hugo source, compile, install
RUN cd /tmp && curl -JLO https://github.com/gohugoio/hugo/archive/refs/tags/v${HUGO_VERSION}.tar.gz \
    && tar xzf hugo-${HUGO_VERSION}.tar.gz \
    && cd hugo-${HUGO_VERSION} \
    && go get github.com/OhYee/goldmark-plantuml@v1.0.3
# Hard-coded files for now, specific to Hugo 0.82.0
COPY ./docker_assets/convert.go /tmp/hugo-${HUGO_VERSION}/markup/goldmark/convert.go
COPY ./docker_assets/config.go /tmp/hugo-${HUGO_VERSION}/markup/goldmark/goldmark_config/config.go
RUN cd /tmp/hugo-${HUGO_VERSION} \
    && go install --tags extended \
    && mv $HOME/go/bin/hugo /usr/local/bin

# Install plantuml
RUN mkdir -p /opt/plantuml && cd /opt/plantuml \
    && UML=http://sourceforge.net/projects/plantuml/files/plantuml.jar/download \
    && curl -JLO ${UML}
COPY ./docker_assets/plantuml /usr/local/bin/plantuml
RUN chmod a+x /usr/local/bin/plantuml

# install ASCIIDOC support
RUN gem install --no-document asciidoctor asciidoctor-revealjs asciidoctor-html5s \
    rouge asciidoctor-confluence asciidoctor-diagram coderay pygments.rb

# Clean up image
RUN rm -rf /tmp/*


RUN mkdir ${DOCUMENT_DIR}
WORKDIR ${DOCUMENT_DIR}

VOLUME ${DOCUMENT_DIR}
ENV CLASSPATH=/opt/plantuml
ENV PATH=${DOCUMENT_DIR}:$PATH
CMD ["hugo","server","--bind","0.0.0.0"]

HEALTHCHECK --interval=2s --timeout=3s \
  CMD curl -f http://localhost:1313/ || exit 1

